### ISSUE TITLE
After update 0.91, the resolution cannot be set.

### ISSUE THREAD

**Issue by xwpd** [ahmad1abbadi/darkos#21]
![WechatIMG645](https://github.com/ahmad1abbadi/darkos/assets/17465049/ee4b922c-40fb-4666-991f-ac7485c950eb)

There is this error message and the resolution cannot be obtained.
Now only 800X600 can be used

**Comment by ahmad1abbadi** [comment]
it can be set by clicking right click on darkos configuration app then resolution
