### ISSUE TITLE
Display resolusion bug

### ISSUE THREAD

**Issue by miyatch** [ahmad1abbadi/darkos#22]
After recently updating the OS, a message like this started appearing at startup, and Termux:X11's 'Display resolution' was now fixed to 'custum' and '800x600'.
![Screenshot_20240428-203953](https://github.com/ahmad1abbadi/darkos/assets/51681142/e35626e0-f2af-463c-b03e-22dd834bfba7)
![Screenshot_20240428-204134](https://github.com/ahmad1abbadi/darkos/assets/51681142/16844ddd-5e58-4be3-a15e-2106948f77fb)
If you change it while the OS is starting up, the desktop will be in a strange state.
![Screenshot_20240428-204147](https://github.com/ahmad1abbadi/darkos/assets/51681142/d04e4773-8d0a-41b6-be09-f38963ae4c3d)
![Screenshot_20240428-203502](https://github.com/ahmad1abbadi/darkos/assets/51681142/3695960e-90d0-4592-b4e1-1e15ab2eb1d1)
Please improve.

**Comment by ahmad1abbadi** [comment]
it's not a problem at all you cab just change resolution from inside wine by right click on darkos configuration app and select resolution
