### ISSUE TITLE
Safe mode unavailable

### ISSUE THREAD

**Issue by DYNAMIX30** [ahmad1abbadi/darkos#33]
![IMG_20240529_005406](https://github.com/ahmad1abbadi/darkos/assets/81133314/95bd5c94-7659-4642-9ca7-75a9c5e66891)
 I dont know what happened but i cant acces safemode...

**Comment by sabamdarif** [comment]
pkg install python-pip -y
pip install tqdm

**Comment by sabamdarif** [comment]
> ![IMG_20240529_005406](https://private-user-images.githubusercontent.com/81133314/334595773-95bd5c94-7659-4642-9ca7-75a9c5e66891.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMjk4NjUsIm5iZiI6MTcxNzEyOTU2NSwicGF0aCI6Ii84MTEzMzMxNC8zMzQ1OTU3NzMtOTViZDVjOTQtNzY1OS00NjQyLTljYTctNzVhOWM1ZTY2ODkxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA0MjYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMTNlM2U3NzkzNTZhN2ViYjNkZjdiYTA2NjNhNjJkZjZlZDlhZGQ3MzlkMmFjYzlkOGY2MjViMjIyMjM4NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yFoKZqvqHS6Bf39tzGe-njBYaHapv2vNWkUkJBftgPU) I dont know what happened but i cant acces safemode...

pkg install python-pip -y
pip install tqdm

Run this on termux then try again
