### ISSUE TITLE
MangoHud isn't showing at all

### ISSUE THREAD

**Issue by GabiAle97** [ahmad1abbadi/darkos#4]
No matter how many times I try it, the "toggle mangohud" button shows up even after a reboot. How does it work? Is there a way to activate it manually?

**Comment by ahmad1abbadi** [comment]
there is fix mangohud in safe mode

**Comment by GabiAle97** [comment]
Still nothing, it can't be activated on the config screen, and it doesn't shows up when opening a game either

**Comment by ahmad1abbadi** [comment]
fixed in update 0.88 beta
