### ISSUE TITLE
Can't change resolution

### ISSUE THREAD

**Issue by Fractal420** [ahmad1abbadi/darkos#45]
Standard resolution is 800x600 which is too small for me, but when i change it, it makes small window in corner (like 75% of screen is dark, or have logo of dark os, but i can use only small window), after reboot it's coming back to 800x600 stretched to full screen.
Device: 
ROG phone 6 pro 
Screen resolution 2448x1080

**Comment by Kalisz420** [comment]
![Screenshot_20240702-004640](https://github.com/ahmad1abbadi/darkos/assets/81500112/a8da1d13-68bb-429d-a8f7-d10daaa8e2ef)
![Screenshot_20240702-004644](https://github.com/ahmad1abbadi/darkos/assets/81500112/044f16bc-721b-4c2f-a1da-cebb56a9c3d9)
![Screenshot_20240702-004714](https://github.com/ahmad1abbadi/darkos/assets/81500112/3c4bc56d-8623-4ba5-89d7-373a220c18de)

**Comment by ahmad1abbadi** [comment]
change resolution from inside Darkos configuration app

**Comment by Fractal420** [comment]
Thank you!
