### ISSUE TITLE
Steam updating forever

### ISSUE THREAD

**Issue by Matmoba** [ahmad1abbadi/darkos#51]
Every time I try to open steam it never ends the update. I downloaded steam through the install tweaks menu at dark os configuration and through the .exe file at steam site and both didn't work
![Screenshot_2024-08-17-14-39-38-137_com termux x11](https://github.com/user-attachments/assets/a7f1a510-b456-460b-af3e-c5eafa8098e4)

**Comment by ahmad1abbadi** [comment]
i don't recommend running steam at all because it's memory hunger
